name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ VideoCaption actions ]
  pull_request:
    branches: [ VideoCaption ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
        # Runs a set of commands using the runners shell
      - name: Install dependencies, build and execute test
        run: |
          pip install -r requirements.txt
          bash early_tests.sh
          sudo apt-get install firefox
          wget 'https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz'
          tar -xvzf geckodriver-v0.26.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin
          docker-compose pull backend
          ./keep_alive.sh 120 docker-compose build
          bash docker_test.sh
